### ISSUE TITLE
作業手順の修正について

### ISSUE THREAD

**Issue by smochi** [sotetsuk/algo-rl-ja#66]
瑣末なことですが、[masterからの空のプルリクの作り方](https://github.com/sotetsuk/algo-rl-ja/wiki/master%E3%81%8B%E3%82%89%E7%A9%BA%E3%81%AE%E3%83%97%E3%83%AB%E3%83%AA%E3%82%AF%E3%81%AE%E4%BD%9C%E3%82%8A%E6%96%B9
)の手順5が
\- git push --set-upstream origin プルリクのタイトル
\+ git push --set-upstream origin github上のbranch名

ではという感じがします。
いかがでしょうか？

**Comment by sotetsuk** [comment]
その通りです

**Comment by sotetsuk** [comment]
ちなみに @smochi に必要なブランチとプルリクはすでに作ってあるのでそこで作業してもらうだけで大丈夫です
